# NumPy

NumPy (or Numpy) is a Linear Algebra Library for Python.

Numpy is also incredibly fast, as it has bindings to C libraries.

## Installation Instructions

**If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [0]:
import numpy as np

# Numpy Arrays

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
array1=np.array(my_list)
type(array1)

numpy.ndarray

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [10]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
dim1 = (2,5,5)

print(type(dim1))

np.zeros(dim1)

<class 'tuple'>


array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [25]:
np.linspace(0,200,51)

array([  0.,   4.,   8.,  12.,  16.,  20.,  24.,  28.,  32.,  36.,  40.,
        44.,  48.,  52.,  56.,  60.,  64.,  68.,  72.,  76.,  80.,  84.,
        88.,  92.,  96., 100., 104., 108., 112., 116., 120., 124., 128.,
       132., 136., 140., 144., 148., 152., 156., 160., 164., 168., 172.,
       176., 180., 184., 188., 192., 196., 200.])

In [0]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [31]:
np.random.rand(5)

array([0.15908603, 0.4924306 , 0.66476639, 0.79157939, 0.62555429])

In [34]:
np.random.rand(5,5)

array([[0.96045681, 0.42830232, 0.16030069, 0.56895392, 0.30900952],
       [0.62313323, 0.77624744, 0.84132866, 0.88769757, 0.85681204],
       [0.87638088, 0.79071337, 0.66322349, 0.54853342, 0.96296082],
       [0.6884601 , 0.72431381, 0.46977222, 0.08141335, 0.66783844],
       [0.04486981, 0.30775948, 0.6705264 , 0.86726356, 0.71565844]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [35]:
np.random.randn(2)

array([-0.65997073,  1.11257452])

In [0]:
np.random.randn(5,5)

array([[-0.60684687, -1.16289282, -1.17377026,  0.51901851,  0.10613251],
       [ 0.27983411, -0.70230126,  2.04114473, -0.90424867, -0.452065  ],
       [ 0.21376852,  0.74545453,  0.12306176, -0.5972056 ,  0.18874452],
       [ 1.10670114, -0.87286331,  1.23586692,  0.93857039,  0.09132615],
       [-0.90044774,  0.21117455,  2.09416643,  1.12425554, -0.08552796]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [50]:
np.random.randint(1,1000)

306

In [53]:
np.random.randint(1,100,10)

array([37, 19, 42, 87, 98, 52, 76, 94, 38, 41])

In [0]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
ranarr

array([10, 10, 19, 22, 37,  7,  4, 27, 49, 33])

## Reshape
Returns an array containing the same data with a new shape.

In [57]:
print(arr)

arr.reshape(5,5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [0]:
ranarr

array([45,  0, 19, 23, 14, 11,  1, 15,  4, 46])

In [0]:
ranarr.max()

46

In [0]:
ranarr.argmax()

9

In [0]:
ranarr.min()

0

In [0]:
ranarr.argmin()

1

## Shape

Shape is an attribute that arrays have (not a method):

In [58]:
# Vector
arr.shape

(25,)

In [59]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [0]:
arr.reshape(1,25).shape

(1, 25)

In [60]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [0]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [0]:
arr.dtype

dtype('int64')

# Great Job!